import type { Metadata } from "next";
import { Ibarra_Real_Nova, Public_Sans } from "next/font/google";
import Providers from "@/utils/Providers/Providers";

const ibarraRealNova = Ibarra_Real_Nova({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-ibarraRealNova",
});

const publicSans = Public_Sans({
  weight: ["400"],
  subsets: ["latin"],
  variable: "--font-publicSans",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${ibarraRealNova.variable} ${publicSans.variable}`}
        suppressHydrationWarning={true}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
